name: lang_table
description: >-
  lang_table is a dart plugin to generate string files from a source. Use
  a table to manage all multi-language resources.

version: 0.2.0
homepage: https://github.com/KingWu/lang_table

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  ansicolor: ^2.0.2
  http: ^1.0.0
